# Generated by Django 4.1.7 on 2023-05-08 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.TimeField(default=datetime.time(21, 39, 31, 317522)),
        ),
    ]
