# Generated by Django 4.1.7 on 2023-05-18 23:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_active_auction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='hyperlink',
            field=models.URLField(blank=True, default='/static/img/noimage.jpg'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.TimeField(default=datetime.time(23, 10, 51, 763673)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
