# Generated by Django 4.1.7 on 2023-05-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_winner_alter_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='hyperlink',
            field=models.URLField(blank=True, default='/static/img/noimage.png'),
        ),
    ]
